### ISSUE TITLE
Loading Screen Text Conflicts with Custom Screen Backgrounds's Clean Loading Menu Mode

### ISSUE THREAD

**Issue by WesternSpace** [Casimir255/SeamlessClient#4]
![image](https://github.com/Casimir255/SeamlessClient/assets/80211714/4aa086a0-ff82-4dc9-a385-35daedf2fdc9)

As depicted in the screenshot, the "Nexus & SeamlessClient Made by: Casimir" text overlaps with the loading percentage text. 

You need to enable the Custom Screen Backgrounds plugin in Plugin Loader to reproduce this issue.

**Comment by Casimir255** [comment]
Why is this just now known? I've had that in there for the past year and possibly more

**Comment by WesternSpace** [comment]
I don't know, but I believe that the custom loading screen patches are getting applied when you are loading into a singleplayer world, which I don't remember seeing before the major update to this plugin.

**Comment by Casimir255** [comment]
@WesternGamer So you may be correct there. I've updated it to only patch into servers. I will need 100% control on servers as they are able to provide custom loading screens and I have a few other things I will prob add like MOTD, stats, and some smaller things.

**Comment by Casimir255** [comment]
It is no longer patching/displaying the text loading into a SP game
