### ISSUE TITLE
Game Paused 

### ISSUE THREAD

**Issue by HyperThrone** [Casimir255/SeamlessClient#5]
Hello There , When changing server instances the game pauses for me and I can't do anything . I am forced to restart the game every time .  I am not the only one who has this problem during transit 

![image](https://github.com/Casimir255/SeamlessClient/assets/154635956/1271ba1f-9e32-4401-aa00-d0001209cdaf)

**Comment by Casimir255** [comment]
Yes, this same issue is already being looked into on the PL discord. Please send logs though for a reference.

Looks like it's specific for modded servers.
