### ISSUE TITLE
Link to a decentralized SE server cluster that a server admin can join

### ISSUE THREAD

**Issue by erikpopp** [Casimir255/SeamlessClient#6]
If you know of any decentralized server clusters that use this mod, I would love to see a link on this project's home page on this repo's readme.md.

This mod has the potential to create a SE galaxy similar in scale to Eve Online or Star Citizen.

It would be nice if a server owner who wanted to create a node could simply install a plugin (this or a meta-plugin), join a mailing list/discord/etc., and start contributing to the SE universe.

**Comment by Casimir255** [comment]
Any Nexus Enabled Server can be used with this plugin. There are several large server that use this plugin and its systems
