### ISSUE TITLE
Unable to Pause Game

### ISSUE THREAD

**Issue by MrHerrDoktor** [Casimir255/SeamlessClient#7]
Issue: Unable to pause Offline Games. 

I've narrowed this down to the Seamless plugin. The game is Offline mode. I've tested it by creating a new game without any plugins or mods. Pause will work. I've tested all the other plugins I use and Pause will work (as long as Seamless is not enabled).

I'm doing MES testing and pausing is useful for this. As a workaround I can just disable the plugin, but I hop on my server often to handle player issues. So it can be an annoyance to have to enable/disable a plugin multiple times in a play session.

**Comment by Casimir255** [comment]
How in the world do you even pause the game?

**Comment by MrHerrDoktor** [comment]
In an offline game, it’ll pause when you Esc to the menu. But only if you
don’t have the seamless plugin installed.

**Comment by Casimir255** [comment]
This should be fixed in next update
