### ISSUE TITLE
Issue with safezone differences between nexus sectors

### ISSUE THREAD

**Issue by Thermi** [Casimir255/SeamlessClient#8]
When switching nexus sectors that have differing safezone settings, the setting of the destination sector is not applied.

**Comment by Casimir255** [comment]
Is this a game config safezone setting? If so I'm not finding any specific safezone setting

**Comment by Casimir255** [comment]
Please add more detail with the issue and what specific safezone setting that is not applying

**Comment by Thermi** [comment]
These are the sandbox settings:

Sandbox.sbc PVE
```
    <MyObjectBuilder_SessionComponent xsi:type="MyObjectBuilder_SessionComponentSafeZones">
      <AllowedActions>Drilling Welding Grinding Building LandingGearLock ConvertToStation BuildingProjections</AllowedActions>
    </MyObjectBuilder_SessionComponent>
```

Sandbox.sbc PVP
```
    <MyObjectBuilder_SessionComponent xsi:type="MyObjectBuilder_SessionComponentSafeZones">
      <AllowedActions>All</AllowedActions>
    </MyObjectBuilder_SessionComponent>
```

What is not being correctly changed is the ability to shoot weapons. It impacts both weaponcore based blocks as well as the vanilla handheld weapons. my client allows me to "shoot" the vanilla assault rifles after moving from a sector where shooting IS allowed to a sector where shooting is NOT alllowed. However with "shoot" I mean I can click and it seems to consume ammunition, and I see a hit marker, but there is no bullet or bullet trail and there is no actual damage. Reconnecting via F5 fixes that.

When moving from a sector where shooting is NOT allowed to a sector where shooting IS allowed, the weaponcore based weapon blocks can not shoot. They can lock, reload, ..., but they can not shoot. Reconnecting via F5 fixes that.

EDIT: Info from admin:


> In the game, it's named “Global Permissions.”

**Comment by Casimir255** [comment]
Should be fixed on latest update
